#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
DOCS_DIR="$ROOT_DIR/docs"
DOXYFILE="$DOCS_DIR/Doxyfile"

mkdir -p "$DOCS_DIR"

cat > "$DOXYFILE" <<'DOXY'
# Doxygen configuration generated by generate_docs.sh
PROJECT_NAME           = "qt_coffee"
OUTPUT_DIRECTORY       = docs/build
CREATE_SUBDIRS         = YES

INPUT                  = include src
RECURSIVE              = NO
FILE_PATTERNS          = *.h *.hpp *.c *.cpp

EXTRACT_ALL            = YES
EXTRACT_PRIVATE        = YES
EXTRACT_STATIC         = YES
EXTRACT_LOCAL_CLASSES  = YES

GENERATE_HTML          = YES
HTML_OUTPUT            = html
GENERATE_LATEX         = NO

GENERATE_TREEVIEW      = YES
USE_MDFILE_AS_MAINPAGE = README.md

SOURCE_BROWSER         = YES
INLINE_SOURCES         = YES
REFERENCED_BY_RELATION = YES
REFERENCES_RELATION    = YES

HAVE_DOT               = YES
DOT_NUM_THREADS        = 0
CALL_GRAPH             = YES
CALLER_GRAPH           = YES
DOT_IMAGE_FORMAT       = svg

GENERATE_XML           = NO

QUIET                  = NO
WARNINGS               = YES
DOXY

echo "Running doxygen (this may take a few seconds)..."
doxygen "$DOXYFILE"

HTML_INDEX="$ROOT_DIR/docs/build/html/index.html"
if [[ -f "$HTML_INDEX" ]]; then
  echo "Documentation generated: $HTML_INDEX"
else
  echo "Doxygen finished but index not found. Check $ROOT_DIR/docs/build for output." >&2
fi

echo "Tips: open the index with 'xdg-open $HTML_INDEX' or a browser of your choice."
